import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Footer from './Components/Footer'
import Navbar from "./Components/Navbar";
import { Providers } from './providers'
import {
  ClerkProvider,
  SignInButton,
  SignedIn,
  SignedOut,
  UserButton
} from '@clerk/nextjs'

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "EmpiricalConstruction",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider publishableKey={'pk_test_YnVzeS1kb2ctOTQuY2xlcmsuYWNjb3VudHMuZGV2JA'}>
    <html lang="en">
      <body className={inter.className}><Providers>
        <Navbar/>
      {children}
      <Footer/>
      </Providers></body>
    </html>
    </ClerkProvider>
  );
}
